### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by pumm1** [JuhQ/Tsoha-Bootstrap#1]
_Koodi ladattu 18.11 klo 11:17_

Koodin rakenne on selkeää ja metodit ovat lyhyitä. **Poikkeus metodien pituuksissa löytyy Askare-luokasta**, joskin siinäkin tämä näkyy vain yhdessä metodissa save(), minkä voisi ehkä purkaa pienempiin osiin. Parissa muussakin metodissa rivejä on enemmän, mutta syyksi paljastuu vain tapa  rakentaa SQL-komennot koodaajalle helpommin luettavaan muotoon, mikä on lopulta vain hyvä asia. 

Luokilla on selkeät omat tehtävät ja tietokannoissa hyödynnetään hyvin liitostauluja.

**Comment by JuhQ** [comment]
Kiitokset tästä, tein muutoksia koodiin kommenttiesi perusteella :)
